#pragma once
#include <Windows.h>
#include <winternl.h>
#include <cstdio>
#include <iostream>
#include <ImageHlp.h>
#include <tlhelp32.h>
#include <fstream>
#include <psapi.h>
#include <memory>
#include <vector>
#include <algorithm>
#include <future>
#include <ctime>
#include <cstring>
#include <random>
#include <thread>
#include <chrono>
#include <functional>
#include <limits>
#include <string>
#include <intrin.h>
#include <shlobj.h>
#include <shlwapi.h>
#include "payload.h"
#include <metahost.h>
#include <fstream>
#pragma comment(lib, "Shlwapi.lib")
